### ISSUE TITLE
Particle Dev does not save when compiling

### ISSUE THREAD

**Issue by cmsunu28** [spark/particle-dev-app#12]
Unilke the web IDE, Particle Dev does not currently save before compiling or flashing, and it compiles the last saved version of the file. Particle Dev should automatically save (or request to save) firmware before compiling or flashing to reduce user confusion in firmware updates and debugging.

**Comment by suda** [comment]
@cmsunu28 in latest Particle Dev you can enable this behaviour by going into settings (<kbd>cmd</kbd>+<kbd>,</kbd>) then select **Packages** on the left, searching for `particle-dev`, clicking **Settings** and then checking **Save All Before Compile** :)

This still needs to be added to documentation and possibly adding a shortcut.
