### ISSUE TITLE
Particle Dev not showing proper line/file for errors

### ISSUE THREAD

**Issue by bluerockpr** [spark/particle-dev-app#17]
One day a week or so ago, all of a sudden, when I get an error, and display it and click on the line, you get a blank screen.

This is because the file its point to is within a folder called /workspace/. Everything else is correct after it, as in the file name and line/char numbers.

Where did this come from. The problem is that you cannot click on the line to go to the line number, you get a blank screen.

I did absolutely nothing to change the environment, same stuff I do 100 times a day every day.

Where did /workspace/ come from? What happened, as now the very handy error line "link" does not work.

Thanks

Marcus

**Comment by suda** [comment]
Hi Marcus, it's possible Particle Dev App automatically updated introducing this bug. Can you share the app that causes this issue?

**Comment by jmonster** [comment]
Sorry for being a me-too but I've experienced this since issue since I first started using Particle ~2 months ago. There's nothing special about my setup -- so you should be able to recreate it pretty easily? I'm running macOS and storing my project in the default `~/Particle/Projects` folder.

In particular, it not only has `workspace` prefixed but also insists on referring to my files as `.ino` when I have them saved as `.cpp`.

**Comment by bluerockpr** [comment]
Guys,

I am a Particle developer, but I am not sure what your talking about, are you addressing this to the right person?

**Comment by bluerockpr** [comment]
Guys,

I am a Particle developer, but I am not sure what your talking about, are you addressing this to the right person?

**Comment by suda** [comment]
We introduced a patch that removes the `/workspace` from the paths to the cloud compiler. @bluerockpr / @jmonster are you still experiencing this issue?

**Comment by bluerockpr** [comment]
Yes, how do I get the patch? Thanks

**Comment by suda** [comment]
The patch was applied server side. It is possible that the current Particle Dev App doesn't enable it yet. We're going to release a new version this sprint which should make it work. I'll keep you posted!

**Comment by bluerockpr** [comment]
Thank you very much. Appreciated!

Marcus

**Comment by suda** [comment]
Hi Marcus! We just released Particle Dev App 1.18.0 ( https://github.com/spark/particle-dev-app/releases/tag/v1.18.0 ) with the patch. Feel free to grab it!
