### ISSUE TITLE
compiler timed out or encountered an error

### ISSUE THREAD

**Issue by Raelx** [spark/particle-dev-app#18]
I've been having this problem for a few weeks on two different machines (one Win10, one Win7) using the same Particle login. If there are any compile errors even a single missing semicolon Dev returns the error "compiler timed out or encountered an error" with no information about where or what the error is. If the code is clean it will compile and left you flash. This is not intermittent but is 100% of the time.

I have tried logging out and back in, no change. Reinstall Dev, no change. Install CLI log in and out of that and Dev, no change. How do i get all traces of Dev and user info off my machine? After i reinstall Dev it starts up and I'm still logged in and back in the last folder i was in. If i could clear this out maybe it would help.

Seems I'm not the only one having this problem:
https://community.particle.io/t/error-message-on-ide-dev/33599
https://community.particle.io/t/compiler-timed-out-or-encountered-an-error/30581/21

**Comment by sidwarkd** [comment]
+1 on this. Do we have an idea on timeframe for a fix?

**Comment by suda** [comment]
I'm happy to say we just released [Particle Dev App 1.18.0](https://github.com/spark/particle-dev-app/releases/tag/v1.18.0) that bundles with fixes for those issues! After launching Dev it should automatically update :)

**Comment by sidwarkd** [comment]
👍👍👍🔥🔥🔥
