### ISSUE TITLE
Particle library format is incompatible with Arduino library format

### ISSUE THREAD

**Issue by innermatrix** [spark/particle-dev-app#3]
Right now, as far as I can tell, it's impossible for the same github repo to contain code for a library that works on Arduino hardware and Particle hardware, due to the fact that Particle IDE demands lib/firmware and Arduino demands lib/src for source location. 

This is a huge problem. We won't get any traction for Particle support in official libraries from Arduino component vendors if they have to maintain a separate repo for Particle libraries. The process of porting libraries to Particle has to be simpler. 

Please do something about this. It could be as simple as adding a config option to spark.json that specifies the source root, or as complicated as supporting the Arduino IDE 1.5 library format out of the box. 

As it stands, we are ending up with shitty community forks of Arduino libraries that constantly fall out of sync with their upstream versions, or don't compile in the first place, because the community doesn't have the time to keep up with all the upstream changes.

I don't want to maintain my own fork for every component I use. I don't want to use the fork ported by someone who had 10 minutes to do in the middle of one of their projects. I want vendors to be able to easily port their Arduino libraries to Particle, and right now that is too hard.

**Comment by dmiddlecamp** [comment]
:+1:  -- I think some work is being done to improve the compatibility / reuse of existing libraries.  I think @suda is the expert on this at the moment

**Comment by suda** [comment]
@airbornemint you're 100% correct. We're working on a never version of libraries system which should solve all issues you mentioned. We'll share more info on the community soon.

**Comment by innermatrix** [comment]
Dammit, every time I file a bug about something major, I find out you are already fixing it :-) Keep it up!

**Comment by zsup** [comment]
Keep the input coming anyway, it's helpful for us to prioritize our efforts! but yeah, your comment is spot-on; when we built our library system, Arduino's didn't exist yet, and now that they have one we have to go back and make ourselves compatible.

**Comment by suda** [comment]
Recently we [released libraries V2](https://docs.particle.io/guide/tools-and-features/libraries/) which are fully Arduino compatible :)
